--- 
abstract: the uri dispatcher
author: 
  - Tokuhiro Matsuno <tokuhirom@gmail.com>
build_requires: 
  Test::MockObject: 0
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTTPx-Dispatcher
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0.3
  Exporter: 5.58
  HTTP::Request: 1.4
  perl: 5.8.0
version: 0.04
